export const issueConstants = {
    GISSUE_START: 'FETCH_ISSUE_START',
    GISSUE_SUCCESS: 'FETCH_ISSUE_SUCCESS',
    GISSUE_FAIL: 'FETCH_ISSUE_FAIL',

    UISSUE_START: 'PUT_ISSUE_START',
    UISSUE_SUCCESS: 'PUT_ISSUE_SUCCESS',
    UISSUE_FAIL: 'PUT_ISSUE_FAIL',
      
    DISSUE_REQUEST: 'DEL_ISSUE_START',
    DISSUE_SUCCESS: 'DEL_ISSUE_SUCCESS',
    DISSUE_FAILURE: 'DEL_ISSUE_FAILURE',

    PISSUE_START: 'POST_ISSUE_START',
    PISSUE_SUCCESS: 'POST_ISSUE_SUCCESS',
    PISSUE_FAIL: 'POST_ISSUE_FAIL',
};