export const userConstants = {
    REG_START: 'REGISTER_USER_START',
    REG_SUCCESS: 'REGISTER_USER_SUCCESS',
    REG_FAIL: 'REGISTER_USER_FAIL',

    LOGIN_START: 'LOGIN_USER_START',
    LOGIN_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_FAIL: 'LOGIN_USER_FAIL',

    LOGOUT: 'LOGOUT',

    // GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    // GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    // GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    FETCH_USER_START = 'FETCH_USER_START',
    FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
    FETCH_USER_FAIL = 'FETCH_USER_FAIL',


    DELETE_REQUEST: 'DEL_USER_START',
    DELETE_SUCCESS: 'DEL_USER_SUCCESS',
    DELETE_FAILURE: 'DEL_USER_FAILURE',

    UPDATE_START: 'UPDATE_USER_START',
    UPDATE_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_FAIL: 'UPDATE_USER_FAIL',
};